#!/usr/bin/zsh
autoload colors
if [ "$terminfo[colors]" -gt 8 ]; then
	colors
fi
PROJECT_FOLDER="$(git rev-parse --show-toplevel)"
PROJECT_NAME="$(basename $PROJECT_FOLDER)"
cd $PROJECT_FOLDER

PROJECT_DOCS_FOLDER="$(eval echo $(workshop-config projects.docs_folder))"
if [ -f "docs/source/conf.py" ]; then
	if [ ! -z "$PROJECT_DOCS_FOLDER" ]; then
		print_status "Building the latest documentation with Sphinx"
		sphinx-build -b html docs/source "$PROJECT_DOCS_FOLDER/$PROJECT_NAME" &> /dev/null
		if [ $? -ne 0 ]; then
			print_error "Sphinx documentation build did not complete successfully"
			exit
		fi
	fi
fi
